Add regression test of returning pinned mut opaque type
Currently fails to build:

    error[E0308]: mismatched types
      --> tests/ffi/module.rs:18:1
       |
    18 | #[cxx::bridge(namespace = "tests")]
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `Pin`, found `&mut _`
       |
       = note:         expected struct `Pin<&mut other::E>`
               found mutable reference `&mut _`
       = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

because we are generating this incorrect code on the Rust side:

    pub fn c_return_opaque_mut_pin(e: ::std::pin::Pin<&mut E>) -> ::std::pin::Pin<&mut E> {
        extern "C" {
            #[link_name = "tests$cxxbridge1$c_return_opaque_mut_pin"]
            fn __c_return_opaque_mut_pin(e: *mut ::std::ffi::c_void)
                -> *mut ::std::ffi::c_void;
        }
        unsafe {
            &mut *__c_return_opaque_mut_pin(
                ::std::pin::Pin::into_inner_unchecked(e) as *mut E as *mut ::std::ffi::c_void
            )
            .cast()
        }
    }