Delete buck1 build from CI
This job began failing today due to some GitHub Actions change. We'll be
replacing it with a buck2 build shortly anyway so it's not worth
debugging now.

    Traceback (most recent call last):
      File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
        exec(code, run_globals)
      File "/home/runner/work/cxx/cxx/bin/buck/__main__.py", line 25, in <module>
      File "/home/runner/work/cxx/cxx/bin/buck/.bootstrap/_pex/pex_bootstrapper.py", line 92, in bootstrap_pex
      File "/home/runner/work/cxx/cxx/bin/buck/.bootstrap/_pex/finders.py", line 22, in <module>
      File "/home/runner/work/cxx/cxx/bin/buck/.bootstrap/pkg_resources/__init__.py", line 32, in <module>
    ModuleNotFoundError: No module named 'symbol'