Add regression test for issue 739
Currently fails to build.

    error[E0261]: use of undeclared lifetime name `'a`
       --> tests/ffi/lib.rs:162:59
        |
    23  | #[cxx::bridge(namespace = "tests")]
        |                                    - lifetime `'a` is missing in item created through this procedural macro
    ...
    162 |         fn c_take_callback_ref_lifetime<'a>(callback: fn(&'a String));
        |                                                           ^^ undeclared lifetime
        |
        = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
        = help: if you want to experiment with in-band lifetime bindings, add `#![feature(in_band_lifetimes)]` to the crate attributes
    help: consider making the type lifetime-generic with a new `'a` lifetime
        |
    162 |         fn c_take_callback_ref_lifetime<'a>(callback: for<'a> fn(&'a String));
        |                                                       ^^^^^^^